### ISSUE TITLE
Adopt sendTransaction Logic From Client Library

### ISSUE THREAD

**Issue by orenyodfat** [daostack/migration#206]
this is needed for https://github.com/dOrgTech/DAOcreator

**Comment by ben-kaufman** [comment]
I don't understand how it is related to the migration repo. Transaction replacement can be done through Metamask and adding it to an automated script like we have is problematic.

**Comment by dOrgJelli** [comment]
@ben-kaufman can you describe what you mean by "transaction replacement can be done through Metamask"? Yes Metamask currently supports "speeding up transactions", or replacing your prior one with one of higher gas cost/limit, but dApps need to support this on their end since the txHash the dApp is waiting on will change.

Currently the Client library supports this [like so](https://github.com/daostack/client/blob/0619d59ab844c115191a95a4d282b78072ac7376/src/operation.ts#L110)

I think the migration script should use this [`sendTransaction`](https://github.com/daostack/client/blob/0619d59ab844c115191a95a4d282b78072ac7376/src/operation.ts#L60) function as it (1) supports sped up & canceled transactions and (2) accurately [estimates gas](https://github.com/daostack/client/blob/0619d59ab844c115191a95a4d282b78072ac7376/src/operation.ts#L83) for transactions. Currently when using the migration script for main-net deployments, I'm not able to consistently get my transactions to confirm when using the traditional:
```typescript
const block = await web3.eth.getBlock("latest");
const opts = {
  from: web3.eth.defaultAccount,
  gas: block.gasLimit - 100000
};
```

@orenyodfat IMO I would rename this issue to "Adopt `sendTransaction` Logic From Client Library"

**Comment by ben-kaufman** [comment]
@dOrgJelli I couldn't find there the exact part which supports transaction replacement. As far as I understand, the script needs to know if a replacement transaction was sent and then accordingly switch to use it instead, but I don't see such logic in the client library. Can you please point me to where it is implemented there?

**Comment by dOrgJelli** [comment]
I believe it is [this line](https://github.com/daostack/client/blob/0619d59ab844c115191a95a4d282b78072ac7376/src/operation.ts#L110), a new 'transactionHash' event is sent, but I'd have to test to verify. I would right now but I'm a bit strapped for time and can't. @jellegerbrandy should have the answer to your question (see comments above).

**Comment by dOrgJelli** [comment]
@orenyodfat @ben-kaufman @jellegerbrandy @tspoff 

I'm so sorry for misleading you all, but after running some tests it turns out [this code](https://github.com/daostack/client/blob/0619d59ab844c115191a95a4d282b78072ac7376/src/operation.ts#L60) actually fails to keep track of sped-up transactions. It isn't easy to spot this from within Alchemy because it updates its state from the subgraph, and not from the pending transaction.

Looking into how you keep track of sped up transactions now.

**Comment by dOrgJelli** [comment]
I've posted a potential solution to this here:
https://github.com/daostack/client/issues/318
