### ISSUE TITLE
Don't Set VM + Scheme Params If They're Already Set

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/migration#228]
Currently the migrate-dao script sets params every time. An optimization can be added where it first uses the view functions (getParamsHash + getParams) to see if they're already set, and if so it doesn't send a new transaction.

**Comment by ben-kaufman** [comment]
Thanks, I implemented this check #231, Please take a look and let me know what you think.
I was unable to do this redundancy check for the custom schemes since I have no pre-knowledge n a "non-null" parameters which they must have. That should be fine for now but suggestions to overcome that are welcomed.
